Ding/impl mark region in source 1
moziliar/source-programs pull request #5
Opened 2020-03-09 04:13 UTC by dingyuchen

2020-03-09 05:20 UTC, moziliar requested changes

2020-03-09 05:20 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +    // ALLOCATE_BUMP_TAIL();
Only mark and free region when there's no more free blocks. Do not do it prematurely.

2020-03-09 05:20 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  RES = HEAP[HEAP[C + FIRST_CHILD_SLOT] + LINE_ADDRESS_SLOT];
Just use some register plz... let's keep RES solely for result of a VM instruction

2020-03-09 05:20 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  C = math_floor(A / BLOCK_SIZE) * BLOCK_SIZE;
You could keep track of current block with a header register like CURR_BLOCK or something?

2020-03-09 05:20 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  RES = HEAP[HEAP[C + FIRST_CHILD_SLOT] + LINE_ADDRESS_SLOT];
```suggestion
  RES = HEAP[C + HEAP[C + FIRST_CHILD_SLOT] + LINE_ADDRESS_SLOT];
```
Is there a missing C?

2020-03-09 05:20 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  A = math_floor((A - RES) / LINE_SIZE);
Likewise, could we do this with a CURR_LINE register?

2020-03-10 05:44 UTC, dingyuchen commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  C = math_floor(A / BLOCK_SIZE) * BLOCK_SIZE;
`GET_LINE()` is agnostic and may not always correspond with `BUMP` pointers. We can use it to always follow the `SCAN` pointer, then we will need to nail down design decision first.

2020-03-10 05:46 UTC, dingyuchen commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +    // ALLOCATE_BUMP_TAIL();
Will add this in for next PR.

2020-03-10 05:47 UTC, dingyuchen commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  A = math_floor((A - RES) / LINE_SIZE);
Similar argument for `CURR_BLOCK`

2020-03-10 16:11 UTC, moziliar commented on src/virtual-machines/source-1-with-mark-region-gc.js
> +  C = math_floor(A / BLOCK_SIZE) * BLOCK_SIZE;
Ok point taken

2020-03-28 03:06 UTC, moziliar approved these changes
LGTM

2020-03-28 07:19 UTC, merged